package com.lyrebird.rc.mavlink

import kotlin.math.roundToInt
import kotlin.math.roundToLong
import kotlin.math.sqrt

/**
 * Payload builders for the phase-1 telemetry set.
 *
 * Every builder lists the wire field order in a comment above it. That order is not editorial: it
 * is generated by MAVLink from the message definition (base fields sorted by descending type size,
 * ties broken by declaration order, then extension fields in declaration order) and appending in
 * any other order corrupts every field after the mistake without any checksum complaining. The
 * orders here were generated from upstream `common.xml`.
 */
internal object MavlinkMessages {

    private const val DEG_TO_E7 = 1e7
    private const val M_TO_MM = 1000.0
    private const val MPS_TO_CMPS = 100.0
    private const val DEG_TO_CDEG = 100.0
    private const val DEG_TO_RAD = Math.PI / 180.0

    /**
     * The mode to report for a snapshot: MISSION while the onboard sequencer is flying, else the
     * mode DJI reports. The sequencer drives the aircraft through virtual stick, which DJI calls
     * VIRTUAL_STICK — a ground station reading that as OFFBOARD would never see the vehicle in
     * mission mode even though a mission is flying.
     */
    private fun modeOf(snapshot: MavlinkSnapshot): MavlinkFlightMode =
        if (snapshot.flightMode == "GO_HOME") {
            // RTH supersedes everything: an RTH that interrupted a mission must read as Return,
            // not as the mission that is no longer flying.
            MavlinkFlightMode.SAFE_RECOVERY
        } else if (snapshot.missionActive) {
            MavlinkFlightMode.MISSION
        } else {
            MavlinkFlightMode.fromDjiMode(snapshot.flightMode, snapshot.manualOverrideActive)
        }

    /** custom_mode(u32), type(u8), autopilot(u8), base_mode(u8), system_status(u8), mavlink_version(u8) */
    fun heartbeat(snapshot: MavlinkSnapshot): ByteArray {
        val mode = modeOf(snapshot)

        // Only flags backed by something real. GUIDED is reported when an autonomous mode is
        // actually flying the aircraft; MANUAL_INPUT when the pilot has the sticks.
        var baseMode = Mav.MODE_FLAG_CUSTOM_MODE_ENABLED
        // Armed stands on real motor activity, or on an accepted ARM command — DJI has no
        // arming state, so without the commanded arm a ground station's arm wait times out.
        if (snapshot.motorsRunning || snapshot.armedCommanded) {
            baseMode = baseMode or Mav.MODE_FLAG_SAFETY_ARMED
        }
        if (mode.guided) baseMode = baseMode or Mav.MODE_FLAG_GUIDED_ENABLED
        if (mode.manualInput) baseMode = baseMode or Mav.MODE_FLAG_MANUAL_INPUT_ENABLED
        if (snapshot.satelliteCount > GPS_STABILIZED_SATELLITES) {
            baseMode = baseMode or Mav.MODE_FLAG_STABILIZE_ENABLED
        }

        val systemStatus = when {
            snapshot.motorsRunning -> Mav.STATE_ACTIVE
            snapshot.flightMode == "UNKNOWN" -> Mav.STATE_UNINIT
            else -> Mav.STATE_STANDBY
        }

        return PayloadWriter()
            .u32(mode.customMode.toLong())
            .u8(Mav.TYPE_QUADROTOR)
            .u8(Mav.AUTOPILOT_PX4)
            .u8(baseMode)
            .u8(systemStatus)
            .u8(Mav.MAVLINK_VERSION)
            .build()
    }

    /** vtol_state(u8), landed_state(u8) */
    fun extendedSysState(snapshot: MavlinkSnapshot): ByteArray {
        val mode = modeOf(snapshot)
        val landedState = when {
            !snapshot.motorsRunning -> Mav.LANDED_STATE_ON_GROUND
            mode == MavlinkFlightMode.LAND -> Mav.LANDED_STATE_LANDING
            mode == MavlinkFlightMode.TAKEOFF -> Mav.LANDED_STATE_TAKEOFF
            else -> Mav.LANDED_STATE_IN_AIR
        }
        return PayloadWriter()
            .u8(Mav.VTOL_STATE_MC)
            .u8(landedState)
            .build()
    }

    /**
     * The camera component's heartbeat. Same layout as [heartbeat], but it announces a camera
     * rather than a vehicle, and carries no mode or armed state — those belong to the aircraft.
     */
    fun cameraHeartbeat(): ByteArray =
        PayloadWriter()
            .u32(0) // custom_mode
            .u8(Mav.TYPE_CAMERA)
            .u8(Mav.AUTOPILOT_INVALID)
            .u8(0) // base_mode
            .u8(Mav.STATE_ACTIVE)
            .u8(Mav.MAVLINK_VERSION)
            .build()

    /**
     * present(u32), enabled(u32), health(u32), load(u16), voltage_battery(u16),
     * current_battery(i16), drop_rate_comm(u16), errors_comm(u16), errors_count1..4(u16),
     * battery_remaining(i8)
     */
    fun sysStatus(snapshot: MavlinkSnapshot): ByteArray {
        var sensors = Mav.SENSOR_3D_GYRO or Mav.SENSOR_3D_ACCEL or Mav.SENSOR_3D_MAG or
            Mav.SENSOR_ABSOLUTE_PRESSURE or Mav.SENSOR_ATTITUDE_STABILIZATION or
            Mav.SENSOR_YAW_POSITION or Mav.SENSOR_Z_ALTITUDE_CONTROL or
            Mav.SENSOR_XY_POSITION_CONTROL or Mav.SENSOR_BATTERY
        val gpsHealthy = snapshot.satelliteCount >= GPS_FIX_3D_SATELLITES
        sensors = sensors or Mav.SENSOR_GPS

        val health = if (gpsHealthy) sensors else sensors and Mav.SENSOR_GPS.inv()

        return PayloadWriter()
            .u32(sensors.toLong())
            .u32(sensors.toLong())
            .u32(health.toLong())
            .u16(0) // load: not measured
            .u16(0) // voltage_battery: not read from the SDK yet, 0 = unknown
            .i16(-1) // current_battery: unknown
            .u16(0) // drop_rate_comm
            .u16(0) // errors_comm
            .u16(0).u16(0).u16(0).u16(0)
            .i8(snapshot.batteryPercent.coerceIn(MavlinkSnapshot.INVALID_BATTERY, PERCENT_MAX))
            .build()
    }

    /**
     * time_usec(u64), lat(i32), lon(i32), alt(i32), eph(u16), epv(u16), vel(u16), cog(u16),
     * fix_type(u8), satellites_visible(u8)
     */
    fun gpsRawInt(snapshot: MavlinkSnapshot, timeUsec: Long): ByteArray {
        val groundSpeed = groundSpeedMps(snapshot)
        return PayloadWriter()
            .u64(timeUsec)
            .i32(degToE7(snapshot.latitudeDeg))
            .i32(degToE7(snapshot.longitudeDeg))
            .i32(metresToMm(snapshot.altitudeAslM))
            // DJI does not expose HDOP/VDOP, so both are reported unknown rather than guessed.
            .u16(MavlinkSnapshot.UINT16_UNKNOWN)
            .u16(MavlinkSnapshot.UINT16_UNKNOWN)
            .u16((groundSpeed * MPS_TO_CMPS).roundToInt().coerceIn(0, MavlinkSnapshot.UINT16_UNKNOWN))
            .u16(headingCdeg(snapshot.headingDeg))
            .u8(gpsFixType(snapshot.satelliteCount))
            .u8(snapshot.satelliteCount.coerceIn(0, U8_MAX))
            .build()
    }

    /** time_boot_ms(u32), roll(f), pitch(f), yaw(f), rollspeed(f), pitchspeed(f), yawspeed(f) */
    fun attitude(snapshot: MavlinkSnapshot, timeBootMs: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .f32((snapshot.rollDeg * DEG_TO_RAD).toFloat())
            .f32((snapshot.pitchDeg * DEG_TO_RAD).toFloat())
            .f32((wrapPi(snapshot.yawDeg) * DEG_TO_RAD).toFloat())
            // Angular rates are not exposed by the DJI SDK telemetry Lyrebird reads.
            .f32(0f).f32(0f).f32(0f)
            .build()

    /**
     * time_boot_ms(u32), lat(i32), lon(i32), alt(i32), relative_alt(i32),
     * vx(i16), vy(i16), vz(i16), hdg(u16)
     */
    fun globalPositionInt(snapshot: MavlinkSnapshot, timeBootMs: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .i32(degToE7(snapshot.latitudeDeg))
            .i32(degToE7(snapshot.longitudeDeg))
            .i32(metresToMm(snapshot.altitudeAslM))
            .i32(metresToMm(snapshot.altitudeAglM))
            .i16(mpsToCmps(snapshot.velocityNorthMps))
            .i16(mpsToCmps(snapshot.velocityEastMps))
            .i16(mpsToCmps(snapshot.velocityDownMps))
            .u16(headingCdeg(snapshot.headingDeg))
            .build()

    /** airspeed(f), groundspeed(f), alt(f), climb(f), heading(i16), throttle(u16) */
    fun vfrHud(snapshot: MavlinkSnapshot): ByteArray {
        val groundSpeed = groundSpeedMps(snapshot)
        return PayloadWriter()
            // DJI reports no airspeed; ground speed is repeated, as RosettaDrone also does, and
            // this is documented rather than silently implied.
            .f32(groundSpeed.toFloat())
            .f32(groundSpeed.toFloat())
            .f32(snapshot.altitudeAslM.toFloat())
            // MAVLink climb rate is positive up; DJI's z velocity is positive down.
            .f32((-snapshot.velocityDownMps).toFloat())
            .i16(((snapshot.headingDeg % FULL_CIRCLE_DEG + FULL_CIRCLE_DEG) % FULL_CIRCLE_DEG).roundToInt())
            .u16(0) // throttle: not exposed
            .build()
    }

    /**
     * current_consumed(i32), energy_consumed(i32), temperature(i16), voltages(u16[10]),
     * current_battery(i16), id(u8), battery_function(u8), type(u8), battery_remaining(i8),
     * [ext] time_remaining(i32)
     *
     * `time_remaining` is a MAVLink 2 extension field — it is the reason Lyrebird's
     * `remainingFlightTime` has a standard home at all, and it could not have been added under
     * MAVLink 1.
     */
    fun batteryStatus(snapshot: MavlinkSnapshot): ByteArray =
        PayloadWriter()
            .i32(-1) // current_consumed: unknown
            .i32(-1) // energy_consumed: unknown
            .i16(MavlinkSnapshot.INT16_UNKNOWN) // temperature: unknown
            // Per-cell voltages are not read from the SDK; UINT16_MAX is the documented "unknown".
            .u16Array(MavlinkSnapshot.UINT16_UNKNOWN, VOLTAGE_CELLS)
            .i16(-1) // current_battery: unknown
            .u8(0) // id
            .u8(0) // battery_function: UNKNOWN
            .u8(0) // type: UNKNOWN
            .i8(snapshot.batteryPercent.coerceIn(MavlinkSnapshot.INVALID_BATTERY, PERCENT_MAX))
            .i32(snapshot.remainingFlightTimeS.coerceAtLeast(0))
            .build()

    /**
     * latitude(i32), longitude(i32), altitude(i32), x(f), y(f), z(f), q(f[4]),
     * approach_x(f), approach_y(f), approach_z(f)
     */
    fun homePosition(snapshot: MavlinkSnapshot): ByteArray =
        PayloadWriter()
            .i32(degToE7(snapshot.homeLatitudeDeg))
            .i32(degToE7(snapshot.homeLongitudeDeg))
            .i32(metresToMm(snapshot.homeAltitudeAslM))
            .f32(0f).f32(0f).f32(0f) // local x/y/z: no local frame is maintained
            .f32Array(IDENTITY_QUATERNION, QUATERNION_LENGTH)
            .f32(0f).f32(0f).f32(0f) // approach vector: not defined
            .build()

    /**
     * capabilities(u64), uid(u64), flight_sw_version(u32), middleware_sw_version(u32),
     * os_sw_version(u32), board_version(u32), vendor_id(u16), product_id(u16),
     * flight_custom_version(u8[8]), middleware_custom_version(u8[8]), os_custom_version(u8[8])
     *
     * Only capabilities that are actually implemented are advertised. Claiming MISSION_INT or FTP
     * before they exist is the same class of mistake as claiming the wrong autopilot.
     *
     * `flight_sw_version` reports PX4 1.15.0 official. QGC's initial-connect state machine parses
     * it and, when it is zero, shows two dialogs on every connect: "supports PX4 Pro firmware
     * 1.4.1 and above" and "not running latest stable firmware, running -1.-1.-1". The version is
     * part of the same compatibility claim the heartbeat already makes by reporting
     * MAV_AUTOPILOT_PX4 — it exists so QGC enables its action buttons — and a current, plausible
     * PX4 version keeps those dialogs from appearing while meaning nothing else.
     */
    fun autopilotVersion(): ByteArray =
        PayloadWriter()
            // FTP is advertised now that the endpoint serves FILE_TRANSFER_PROTOCOL v1, the
            // protocol-discovery rule in the MAVLink FTP spec.
            .u64(Mav.CAP_MAVLINK2 or Mav.CAP_FTP)
            .u64(0) // uid
            .u32(PX4_COMPAT_FLIGHT_SW_VERSION.toLong())
            .u32(0).u32(0).u32(0)
            .u16(0).u16(0)
            .chars("WBbridge", CUSTOM_VERSION_BYTES)
            .zeros(CUSTOM_VERSION_BYTES * 2)
            .build()

    /** severity(u8), text(char[50]) */
    fun statusText(severity: Int, text: String): ByteArray =
        PayloadWriter()
            .u8(severity)
            .chars(text, STATUSTEXT_LENGTH)
            .build()

    /**
     * custom_mode(u32), properties(u32), number_modes(u8), mode_index(u8),
     * standard_mode(u8), mode_name(char[35])
     *
     * One message per mode; a ground station enumerates them to build its mode list. `mode_index`
     * is 1-based. Modes that have a portable `MAV_STANDARD_MODE` identity send it and omit the
     * name — the ground station already knows what to call those. Modes that do not (offboard,
     * manual, DJI's intelligent-flight family) carry a name instead, which is the mechanism that
     * lets Lyrebird describe itself without borrowing another flight stack's mode numbers.
     *
     * Every mode is flagged NOT_USER_SELECTABLE for now: they are reported, not settable, because
     * setting a mode means commanding the aircraft and that belongs with the rest of the command
     * surface.
     */
    fun availableModes(mode: MavlinkFlightMode, index: Int, total: Int): ByteArray =
        PayloadWriter()
            .u32(mode.customMode.toLong())
            .u32(Mav.MODE_PROPERTY_NOT_USER_SELECTABLE)
            .u8(total)
            .u8(index)
            .u8(mode.standardMode)
            .chars(
                if (mode.standardMode == Mav.STANDARD_MODE_NON_STANDARD) mode.displayName else "",
                MODE_NAME_LENGTH
            )
            .build()

    /**
     * custom_mode(u32), intended_custom_mode(u32), standard_mode(u8)
     *
     * `intended_custom_mode` is what the operator asked for, so a ground station can show a failed
     * mode change. Lyrebird does not accept mode commands yet, so intended always equals actual
     * — reporting a different value would imply a transition that never happened.
     */
    fun currentMode(mode: MavlinkFlightMode): ByteArray =
        PayloadWriter()
            .u32(mode.customMode.toLong())
            .u32(mode.customMode.toLong())
            .u8(mode.standardMode)
            .build()

    /**
     * framerate(f), bitrate(u32), flags(u16), resolution_h(u16), resolution_v(u16),
     * rotation(u16), hfov(u16), stream_id(u8)
     *
     * The running-state counterpart to [videoStreamInformation]. QGroundControl polls it after
     * the stream is described; leaving it unanswered produces the same class of half-initialised
     * camera as the settings and storage requests did.
     */
    fun videoStreamStatus(
        framerate: Float,
        widthPx: Int,
        heightPx: Int
    ): ByteArray =
        PayloadWriter()
            .f32(framerate)
            .u32(0) // bitrate: unknown
            .u16(Mav.VIDEO_STREAM_STATUS_RUNNING)
            .u16(widthPx.coerceIn(0, MavlinkSnapshot.UINT16_UNKNOWN))
            .u16(heightPx.coerceIn(0, MavlinkSnapshot.UINT16_UNKNOWN))
            .u16(0) // rotation
            .u16(0) // hfov: unknown
            .u8(STREAM_ID)
            .build()

    /**
     * time_boot_ms(u32), mode_id(u8), [ext] zoomLevel(f), focusLevel(f)
     *
     * QGroundControl requests this as part of bringing a camera up, and its PhotoVideoControl QML
     * reads `cameraMode` straight off the resulting object. Leaving the request unanswered is not
     * neutral: the camera object stays null and the QML throws, which breaks the surrounding
     * controls — including the button that swaps the map and video views.
     */
    fun cameraSettings(timeBootMs: Long, zoomLevel: Float): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .u8(Mav.CAMERA_MODE_VIDEO)
            .f32(zoomLevel)
            .f32(0f) // focusLevel: not exposed
            .build()

    /**
     * time_boot_ms(u32), total_capacity(f), used_capacity(f), available_capacity(f),
     * read_speed(f), write_speed(f), storage_id(u8), storage_count(u8), status(u8)
     *
     * Reported as NOT_SUPPORTED with zero capacities. The DJI card is real, but it is reachable
     * over the HTTP media endpoints rather than MAVLink, and claiming a storage volume we cannot
     * actually enumerate would put figures in the ground station that mean nothing. Answering
     * honestly still completes QGC's camera model, which is what the QML needs.
     */
    fun storageInformation(timeBootMs: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .f32(0f).f32(0f).f32(0f)
            .f32(0f).f32(0f)
            .u8(STORAGE_ID)
            .u8(1) // storage_count
            .u8(Mav.STORAGE_STATUS_NOT_SUPPORTED)
            .build()

    /**
     * seq(u16), target_system(u8), target_component(u8), [ext] mission_type(u8)
     *
     * Asks the ground station for one item during an upload. The upload is a conversation: it
     * announces a count, we request each index in turn, it answers. Requesting by index rather
     * than streaming is what lets a lost item be retried without restarting the plan.
     */
    fun missionRequestInt(seq: Int, targetSystem: Int, targetComponent: Int): ByteArray =
        PayloadWriter()
            .u16(seq)
            .u8(targetSystem)
            .u8(targetComponent)
            .u8(MavlinkMissionStore.MISSION_TYPE_MISSION)
            .build()

    /**
     * target_system(u8), target_component(u8), type(u8), [ext] mission_type(u8)
     *
     * Ends an upload or download. `type` carries a MAV_MISSION_RESULT, so a refusal says which
     * item was wrong rather than failing silently — §11's rule that a silently dropped mission
     * item is a flight-safety bug.
     */
    fun missionAck(result: Int, targetSystem: Int, targetComponent: Int): ByteArray =
        PayloadWriter()
            .u8(targetSystem)
            .u8(targetComponent)
            .u8(result)
            .u8(MavlinkMissionStore.MISSION_TYPE_MISSION)
            .build()

    /**
     * param1(f), param2(f), param3(f), param4(f), x(i32), y(i32), z(f), seq(u16), command(u16),
     * target_system(u8), target_component(u8), frame(u8), current(u8), autocontinue(u8)
     *
     * One item of a stored plan, sent during a download. Latitude and longitude are the scaled
     * integers the INT variant exists for; altitude is a float in metres, relative to home.
     */
    fun missionItemInt(
        item: MissionItem,
        targetSystem: Int,
        targetComponent: Int,
        isCurrent: Boolean
    ): ByteArray =
        PayloadWriter()
            .f32(item.param1)
            .f32(item.param2)
            .f32(item.param3)
            .f32(item.param4)
            .i32(degToE7(item.latitudeDeg))
            .i32(degToE7(item.longitudeDeg))
            .f32(item.altitudeM.toFloat())
            .u16(item.seq)
            .u16(item.command)
            .u8(targetSystem)
            .u8(targetComponent)
            .u8(MAV_FRAME_GLOBAL_RELATIVE_ALT_INT)
            .u8(if (isCurrent) 1 else 0)
            .u8(if (item.autocontinue) 1 else 0)
            .build()

    /**
     * seq(u16), [ext] total(u16), mission_state(u8), mission_mode(u8), mission_id(u32),
     * fence_id(u32), rally_points_id(u32)
     *
     * Streamed so a ground station can show which item is being flown without asking. The
     * `mission_id` changes whenever the stored plan changes, which is how a station notices its
     * cached copy is stale.
     */
    fun missionCurrent(seq: Int, total: Int, state: Int, planId: Int): ByteArray =
        PayloadWriter()
            .u16(seq)
            .u16(total)
            .u8(state)
            .u8(0) // mission_mode: not reported
            .u32(planId.toLong())
            .build()

    /**
     * time_boot_ms(u32), q(float[4]), angular_velocity_x/y/z(f32), failure_flags(u32),
     * flags(u16), target_system(u8), target_component(u8),
     * [ext] delta_yaw(f32), delta_yaw_velocity(f32), gimbal_device_id(u8)
     *
     * The order is mavgen's, not the XML's: MAVLink packs fields largest-first, so failure_flags
     * precedes flags despite being declared after it. Getting that backwards produces a frame
     * with a valid checksum that decodes into nonsense, which is the same failure this package
     * has shipped once before.
     *
     * The standard gimbal v2 attitude report, which Lyrebird is already entitled to send: the
     * camera component advertises the gimbal capability, and a ground station that understands
     * gimbals reads the pointing direction from here rather than from anything Lyrebird-specific.
     *
     * DJI reports two gimbal attitudes — one in the world frame and one relative to the aircraft.
     * The quaternion carries the world-frame attitude, and `delta_yaw` carries the difference,
     * which is exactly the field MAVLink defines for "yaw relative to the vehicle".
     *
     * The wire specifies `delta_yaw` in radians, not degrees. Sending the joint angle as degrees
     * is a units bug that is invisible while the aircraft is still — the joint yaw sits near zero
     * and a zero is a zero in either unit — and shows up the moment the aircraft moves and the
     * gimbal compensates: a receiver converts the field from radians, so a 30-degree joint yaw
     * sent as 30.0 reads back as 1719 degrees. The field was shipped this way once; the
     * regression test pins the radians encoding.
     */
    fun gimbalDeviceAttitudeStatus(snapshot: MavlinkSnapshot, timeBootMs: Long): ByteArray {
        val (w, x, y, z) = eulerToQuaternion(
            snapshot.gimbalRollDeg, snapshot.gimbalPitchDeg, snapshot.gimbalYawDeg
        )
        return PayloadWriter()
            .u32(timeBootMs)
            .f32(w).f32(x).f32(y).f32(z)
            // Angular rates are not reported by DJI. NaN is MAVLink's "unknown" here, which is
            // honest where zero would claim a stationary gimbal.
            .f32(Float.NaN).f32(Float.NaN).f32(Float.NaN)
            .u32(0) // failure_flags: nothing wrong
            .u16(GIMBAL_FLAGS_YAW_IN_VEHICLE_FRAME)
            .u8(0) // target_system: broadcast
            .u8(0) // target_component
            .f32((snapshot.gimbalJointYawDeg * DEG_TO_RAD).toFloat()) // delta_yaw, radians per spec
            .f32(Float.NaN) // delta_yaw_velocity
            .u8(GIMBAL_DEVICE_ID)
            .build()
    }

    /**
     * time_boot_ms(u32), min_distance(u16), max_distance(u16), current_distance(u16), type(u8),
     * id(u8), orientation(u8), covariance(u8), [ext] horizontal_fov, vertical_fov, quaternion,
     * signal_quality(u8)
     *
     * The laser rangefinder as a standard ranging sensor, so a ground station plots the range
     * without knowing anything about Lyrebird. The geo-referenced target point it computes has
     * no standard home and travels in LYREBIRD_STATUS instead.
     */
    fun distanceSensor(distanceMeters: Double, timeBootMs: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .u16(LRF_MIN_DISTANCE_CM)
            .u16(LRF_MAX_DISTANCE_CM)
            .u16((distanceMeters * 100).toInt().coerceIn(0, 0xFFFF))
            .u8(Mav.DISTANCE_SENSOR_TYPE_LASER)
            .u8(0) // id
            .u8(Mav.SENSOR_ROTATION_PITCH_270) // fixed to the gimbal, pointing where it looks
            .u8(0) // covariance: unknown
            .build()

    /**
     * Lyrebird's residue. Field order and offsets come from lyrebird.xml as generated by
     * mavgen — see GroundStation/mavlink/lyrebird.xml, which is the source of truth for both
     * ends and for the CRC_EXTRA of 196.
     */
    fun lyrebirdStatus(snapshot: MavlinkSnapshot, timeBootMs: Long): ByteArray {
        var flags = 0
        if (snapshot.manualOverrideActive) flags = flags or LB_FLAG_MANUAL_OVERRIDE
        if (snapshot.readyToTakeoff) flags = flags or LB_FLAG_READY_TO_TAKEOFF
        if (snapshot.homeSet) flags = flags or LB_FLAG_HOME_SET
        val targetValid = snapshot.lrfTargetLatitudeDeg != null &&
            snapshot.lrfTargetLongitudeDeg != null
        if (targetValid) flags = flags or LB_FLAG_LRF_TARGET_VALID
        if (snapshot.waypointReached) flags = flags or LB_FLAG_WAYPOINT_REACHED
        if (snapshot.yawReached) flags = flags or LB_FLAG_YAW_REACHED
        if (snapshot.altitudeReached) flags = flags or LB_FLAG_ALTITUDE_REACHED

        return PayloadWriter()
            .u32(timeBootMs)
            .i32(degToE7(snapshot.lrfTargetLatitudeDeg ?: 0.0))
            .i32(degToE7(snapshot.lrfTargetLongitudeDeg ?: 0.0))
            .f32((snapshot.lrfTargetAltitudeM ?: 0.0).toFloat())
            .f32(snapshot.maxRadiusCanFlyAndGoHomeM.toFloat())
            .u32(snapshot.waypointSeq)
            .u32(snapshot.yawSeq)
            .u32(snapshot.altitudeSeq)
            .u16(snapshot.timeNeededToGoHomeS.coerceIn(0, 0xFFFF))
            .u16(snapshot.timeNeededToLandS.coerceIn(0, 0xFFFF))
            .u16(snapshot.totalFlightTimeS.coerceIn(0, 0xFFFF))
            .i16(degToCentidegrees(snapshot.gimbalJointPitchDeg))
            .i16(degToCentidegrees(snapshot.gimbalJointRollDeg))
            .u16(snapshot.zoomFocalLengthMm.coerceIn(0, 0xFFFF))
            .u16(snapshot.opticalFocalLengthMm.coerceIn(0, 0xFFFF))
            .u16(snapshot.hybridFocalLengthMm.coerceIn(0, 0xFFFF))
            .u8(snapshot.batteryNeededToGoHomePercent.coerceIn(0, 255))
            .u8(snapshot.batteryNeededToLandPercent.coerceIn(0, 255))
            .u8(flags)
            .chars(snapshot.takeoffBlockReason, TAKEOFF_REASON_LENGTH)
            .build()
    }

    /**
     * http_port(u16), telemetry_port(u16), flags(u8), drone_name(char[20]),
     * ip_address(char[16]), video_mode(char[12])
     *
     * What GET /config would have answered, streamed instead of asked for. Everything in it is
     * static for a session, which is why it is its own message at a slow rate rather than more
     * weight on LYREBIRD_STATUS.
     */
    fun lyrebirdConfig(snapshot: MavlinkSnapshot): ByteArray =
        PayloadWriter()
            .u16(snapshot.httpPort.coerceIn(0, 0xFFFF))
            .u16(snapshot.telemetryPort.coerceIn(0, 0xFFFF))
            .u8(if (snapshot.hasThermal) LB_CONFIG_FLAG_HAS_THERMAL else 0)
            .chars(snapshot.droneName, DRONE_NAME_LENGTH)
            .chars(snapshot.ipAddress, IP_ADDRESS_LENGTH)
            .chars(snapshot.videoMode, VIDEO_MODE_LENGTH)
            .build()

    /**
     * time_boot_ms(u32), frame_id(u32), confidence_threshold(f32), active(u8), target_count(u8),
     * source(char[16])
     *
     * Sent even when nothing is detected, because "detection is off" and "detection is on and
     * sees nothing" are different states and a ground station cannot tell them apart from the
     * absence of target messages alone.
     */
    fun autoSensingStatus(snapshot: MavlinkSnapshot, timeBootMs: Long, frameId: Long): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .u32(frameId)
            .f32(snapshot.detectionConfidenceThreshold)
            .u8(if (snapshot.autoSensingActive) 1 else 0)
            .u8(snapshot.detectedTargets.size.coerceIn(0, 255))
            .chars(snapshot.detectionSource, DETECTION_SOURCE_LENGTH)
            .build()

    /**
     * time_boot_ms(u32), frame_id(u32), left/top/right/bottom(f32), confidence(f32),
     * target_index(u8), target_count(u8), type(char[16])
     *
     * One message per target, the way ADSB_VEHICLE reports traffic. A fixed-size list would have
     * to cap the number of targets; this does not, and a dropped packet costs one target rather
     * than the whole cycle.
     */
    fun autoSensingTarget(
        target: DetectedTargetSnapshot,
        index: Int,
        total: Int,
        timeBootMs: Long,
        frameId: Long
    ): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .u32(frameId)
            .f32(target.left.toFloat())
            .f32(target.top.toFloat())
            .f32(target.right.toFloat())
            .f32(target.bottom.toFloat())
            // NaN rather than zero when the detector did not report one: zero is a confidence.
            .f32(target.confidence?.toFloat() ?: Float.NaN)
            .u8(index.coerceIn(0, 255))
            .u8(total.coerceIn(0, 255))
            .chars(target.type, DETECTION_TYPE_LENGTH)
            .build()

    /** Degrees to centidegrees, clamped to the int16 the wire field is. */
    private fun degToCentidegrees(degrees: Double): Int =
        (degrees * 100).toInt().coerceIn(Short.MIN_VALUE.toInt(), Short.MAX_VALUE.toInt())

    /** ZYX euler angles in degrees to a MAVLink attitude quaternion. */
    private fun eulerToQuaternion(
        rollDeg: Double,
        pitchDeg: Double,
        yawDeg: Double
    ): Quaternion {
        val cr = kotlin.math.cos(Math.toRadians(rollDeg) / 2)
        val sr = kotlin.math.sin(Math.toRadians(rollDeg) / 2)
        val cp = kotlin.math.cos(Math.toRadians(pitchDeg) / 2)
        val sp = kotlin.math.sin(Math.toRadians(pitchDeg) / 2)
        val cy = kotlin.math.cos(Math.toRadians(yawDeg) / 2)
        val sy = kotlin.math.sin(Math.toRadians(yawDeg) / 2)
        return Quaternion(
            (cr * cp * cy + sr * sp * sy).toFloat(),
            (sr * cp * cy - cr * sp * sy).toFloat(),
            (cr * sp * cy + sr * cp * sy).toFloat(),
            (cr * cp * sy - sr * sp * cy).toFloat()
        )
    }

    private data class Quaternion(val w: Float, val x: Float, val y: Float, val z: Float)

    /** seq(u16) — emitted as each waypoint is reached. */
    fun missionItemReached(seq: Int): ByteArray =
        PayloadWriter()
            .u16(seq)
            .build()

    /**
     * param_value(f), param_count(u16), param_index(u16), param_id(char[16]), param_type(u8)
     */
    fun paramValue(name: String, value: Float, count: Int, index: Int): ByteArray =
        PayloadWriter()
            .f32(value)
            .u16(count)
            .u16(index)
            .chars(name, PARAM_ID_LENGTH)
            .u8(Mav.PARAM_TYPE_REAL32)
            .build()

    /**
     * param_id(char[16]), param_value(char[128]), param_type(u8), param_result(u8)
     *
     * The answer to a PARAM_EXT_SET. The value echoed back is what the setting now holds, not
     * what was asked for, so a caller learns from the reply whether the write actually took.
     */
    fun paramExtAck(name: String, value: String, result: Int): ByteArray =
        PayloadWriter()
            .chars(name, PARAM_ID_LENGTH)
            .chars(value, PARAM_EXT_VALUE_LENGTH)
            .u8(Mav.PARAM_EXT_TYPE_CUSTOM)
            .u8(result)
            .build()

    /**
     * param_count(u16), param_index(u16), param_id(char[16]), param_value(char[128]),
     * param_type(u8)
     */
    fun paramExtValue(name: String, value: String, count: Int, index: Int): ByteArray =
        PayloadWriter()
            .u16(count)
            .u16(index)
            .chars(name, PARAM_ID_LENGTH)
            .chars(value, PARAM_EXT_VALUE_LENGTH)
            .u8(Mav.PARAM_EXT_TYPE_CUSTOM)
            .build()

    /**
     * count(u16), target_system(u8), target_component(u8), [ext] mission_type(u8)
     *
     * Opens a plan download, and also answers MISSION_REQUEST_LIST when the store is empty — a
     * count of zero is how a ground station is told there is no plan, and lets it finish the
     * download instead of retrying. [missionType] is echoed back so a station that asked about a
     * geofence or rally points sees the answer belongs to its question.
     */
    fun missionCount(
        count: Int,
        targetSystem: Int,
        targetComponent: Int,
        missionType: Int
    ): ByteArray =
        PayloadWriter()
            .u16(count)
            .u8(targetSystem)
            .u8(targetComponent)
            .u8(missionType)
            .build()

    /**
     * command(u16), result(u8), [ext] progress(u8), result_param2(i32),
     * target_system(u8), target_component(u8)
     *
     * The target fields are extensions, but a ground station uses them to route the ack back to
     * the request it made, so they are always populated rather than left to truncation.
     */
    fun commandAck(
        command: Int,
        result: Int,
        targetSystem: Int,
        targetComponent: Int,
        /**
         * Command-specific return value, which MAVLink defines result_param2 to carry.
         *
         * Lyrebird uses it for the commands whose whole point is to read something back — the
         * rangefinder's distance, the thermal spot temperature — so a caller gets the reading in
         * the ack rather than having to poll telemetry and hope it is looking at the right sample.
         */
        resultValue: Int = 0
    ): ByteArray =
        PayloadWriter()
            .u16(command)
            .u8(result)
            .u8(0) // progress
            .i32(resultValue)
            .u8(targetSystem)
            .u8(targetComponent)
            .build()

    /**
     * time_boot_ms(u32), firmware_version(u32), focal_length(f), sensor_size_h(f),
     * sensor_size_v(f), flags(u32), resolution_h(u16), resolution_v(u16),
     * cam_definition_version(u16), vendor_name(u8[32]), model_name(u8[32]), lens_id(u8),
     * cam_definition_uri(char[140])
     *
     * Claims the video stream plus image and video capture, all of which are now implemented in
     * [MavlinkCommandSink]. The rule that keeps this honest: a capability flag is a promise about
     * the whole microservice behind it, so nothing is claimed here until the messages and commands
     * that support it exist. Capture and recording were deliberately absent until they did.
     *
     * `cam_definition_uri` is left empty: a camera definition file is how per-camera settings get
     * rendered, and there are none to expose until the detection and streaming parameters land.
     */
    /**
     * time_boot_ms(u32), image_interval(f), recording_time_ms(u32), available_capacity(f),
     * image_status(u8), video_status(u8)
     *
     * The message that makes a ground station's record indicator tell the truth. QGroundControl
     * polls it on a 1.5-second timer and drives its record button from `video_status`, so without
     * it the button never reflects reality — in either direction. Recording started from the
     * Lyrebird UI or the RC shows up here too, because the state is read from the aircraft
     * rather than remembered from whatever MAVLink last commanded.
     *
     * `recording_time_ms` is 0: MSDK 5.18 exposes no recording-duration key, and a fabricated
     * elapsed time would be worse than none.
     */
    fun cameraCaptureStatus(
        timeBootMs: Long,
        recording: Boolean,
        capturing: Boolean = false,
        imageCount: Int = 0
    ): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .f32(0f) // image_interval: no interval capture
            .u32(0) // recording_time_ms: not exposed by the SDK
            .f32(0f) // available_capacity: storage is not enumerated, see storageInformation
            .u8(if (capturing) Mav.CAPTURE_STATUS_RUNNING else Mav.CAPTURE_STATUS_IDLE)
            .u8(if (recording) Mav.CAPTURE_STATUS_RUNNING else Mav.CAPTURE_STATUS_IDLE)
            .i32(imageCount)
            .build()

    /**
     * time_utc(u64), time_boot_ms(u32), lat(i32), lon(i32), alt(i32), relative_alt(i32),
     * q(f[4]), image_index(i32), camera_id(u8), capture_result(i8), file_url(char[205])
     *
     * Sent after each shutter. Two things make it worth more than the command ack: it carries the
     * position the photo was taken at, so a ground station can place the image on the map without
     * correlating timestamps; and `image_index` increments, so a receiver can tell that a capture
     * was missed rather than silently losing it.
     *
     * `capture_result` is where a failed shutter is reported honestly — the command is
     * acknowledged as accepted immediately, because tripping a shutter and waiting for the file to
     * appear takes seconds and must not block the endpoint's receive thread.
     */
    fun cameraImageCaptured(
        snapshot: MavlinkSnapshot,
        timeBootMs: Long,
        imageIndex: Int,
        success: Boolean,
        fileName: String
    ): ByteArray =
        PayloadWriter()
            .u64(0) // time_utc: unknown, receivers fall back to time_boot_ms
            .u32(timeBootMs)
            .i32(degToE7(snapshot.latitudeDeg))
            .i32(degToE7(snapshot.longitudeDeg))
            .i32(metresToMm(snapshot.altitudeAslM))
            .i32(metresToMm(snapshot.altitudeAglM))
            // Attitude quaternion is not computed; identity rather than a wrong rotation.
            .f32Array(IDENTITY_QUATERNION, QUATERNION_LENGTH)
            .i32(imageIndex)
            .u8(0) // camera_id: the single camera this component represents
            .i8(if (success) 1 else 0)
            .chars(fileName, FILE_URL_LENGTH)
            .build()

    fun cameraInformation(
        timeBootMs: Long,
        vendorName: String,
        modelName: String
    ): ByteArray =
        PayloadWriter()
            .u32(timeBootMs)
            .u32(0) // firmware_version
            .f32(0f) // focal_length: unknown, varies with the DJI payload fitted
            .f32(0f).f32(0f) // sensor size: unknown
            .u32(
                Mav.CAMERA_CAP_HAS_VIDEO_STREAM or
                    Mav.CAMERA_CAP_CAPTURE_VIDEO or
                    Mav.CAMERA_CAP_CAPTURE_IMAGE
            )
            .u16(0).u16(0) // still-capture resolution: not applicable while capture is unclaimed
            .u16(0) // cam_definition_version
            .chars(vendorName, NAME_FIELD_LENGTH)
            .chars(modelName, NAME_FIELD_LENGTH)
            .u8(0) // lens_id
            .chars("", CAM_DEFINITION_URI_LENGTH)
            .build()

    /**
     * framerate(f), bitrate(u32), flags(u16), resolution_h(u16), resolution_v(u16),
     * rotation(u16), hfov(u16), stream_id(u8), count(u8), type(u8), name(char[32]),
     * uri(char[160]), [ext] encoding(u8), camera_device_id(u8)
     *
     * The URI is what makes this worth sending: QGroundControl's VideoManager reads it, sets its
     * own RTSP URL and video source from it, and starts playing without the operator configuring
     * anything.
     */
    fun videoStreamInformation(
        uri: String,
        name: String,
        framerate: Float,
        widthPx: Int,
        heightPx: Int
    ): ByteArray =
        PayloadWriter()
            .f32(framerate)
            .u32(0) // bitrate: unknown
            .u16(Mav.VIDEO_STREAM_STATUS_RUNNING)
            .u16(widthPx.coerceIn(0, MavlinkSnapshot.UINT16_UNKNOWN))
            .u16(heightPx.coerceIn(0, MavlinkSnapshot.UINT16_UNKNOWN))
            .u16(0) // rotation
            .u16(0) // hfov: unknown
            .u8(STREAM_ID)
            .u8(1) // count: one stream
            .u8(Mav.VIDEO_STREAM_TYPE_RTSP)
            .chars(name, NAME_FIELD_LENGTH)
            .chars(uri, STREAM_URI_LENGTH)
            .u8(Mav.VIDEO_STREAM_ENCODING_H264)
            .build()

    // ---- conversions -------------------------------------------------------

    fun groundSpeedMps(snapshot: MavlinkSnapshot): Double =
        sqrt(
            snapshot.velocityNorthMps * snapshot.velocityNorthMps +
                snapshot.velocityEastMps * snapshot.velocityEastMps
        )

    /** MAVLink GPS fix type, from satellite count — DJI reports no fix type directly. */
    fun gpsFixType(satelliteCount: Int): Int = when {
        satelliteCount >= GPS_FIX_3D_SATELLITES -> GPS_FIX_TYPE_3D
        satelliteCount >= GPS_FIX_2D_SATELLITES -> GPS_FIX_TYPE_2D
        else -> GPS_FIX_TYPE_NO_FIX
    }

    /**
     * Degrees to the 1e-7 degree integers MAVLink uses, clamped to the valid coordinate range.
     *
     * The clamp is not defensive padding. Before a home point is set, the DJI SDK returns an
     * uninitialised latitude around 45836623 degrees; scaled by 1e7 that is 4.6e14, and a bare
     * `.toInt()` wraps it to -1263659053 — which a ground station would plot as latitude
     * -126.4, a value that is not even a latitude. Clamping keeps a bad input visibly bad instead
     * of turning it into a plausible-looking position somewhere else on the planet.
     */
    private fun degToE7(degrees: Double): Int {
        if (degrees.isNaN()) return 0
        val scaled = (degrees * DEG_TO_E7).roundToLong()
        return scaled.coerceIn(MIN_COORD_E7, MAX_COORD_E7).toInt()
    }

    private fun metresToMm(metres: Double): Int = (metres * M_TO_MM).roundToLong().toInt()

    private fun mpsToCmps(mps: Double): Int =
        (mps * MPS_TO_CMPS).roundToInt().coerceIn(Short.MIN_VALUE.toInt(), Short.MAX_VALUE.toInt())

    /** Heading in centidegrees, 0..35999, as GLOBAL_POSITION_INT and GPS_RAW_INT expect. */
    private fun headingCdeg(headingDeg: Double): Int {
        val normalised = ((headingDeg % FULL_CIRCLE_DEG) + FULL_CIRCLE_DEG) % FULL_CIRCLE_DEG
        return (normalised * DEG_TO_CDEG).roundToInt().coerceIn(0, MAX_CDEG)
    }

    /** DJI reports yaw in -180..180 already, but normalise so ATTITUDE never exceeds ±pi. */
    private fun wrapPi(degrees: Double): Double {
        var value = (degrees + HALF_CIRCLE_DEG) % FULL_CIRCLE_DEG
        if (value < 0) value += FULL_CIRCLE_DEG
        return value - HALF_CIRCLE_DEG
    }

    private const val GPS_FIX_TYPE_NO_FIX = 0
    private const val GPS_FIX_TYPE_2D = 2
    private const val GPS_FIX_TYPE_3D = 3
    private const val GPS_FIX_2D_SATELLITES = 4
    private const val GPS_FIX_3D_SATELLITES = 6
    private const val GPS_STABILIZED_SATELLITES = 5
    private const val PERCENT_MAX = 100
    private const val U8_MAX = 255
    private const val VOLTAGE_CELLS = 10
    private const val QUATERNION_LENGTH = 4
    private const val CUSTOM_VERSION_BYTES = 8

    /**
     * PX4 release encoding: (major << 24) | (minor << 16) | (patch << 8) | type, with 0xFF the
     * "official stable" type byte. See [autopilotVersion] for why a version is reported at all.
     */
    private const val PX4_COMPAT_FLIGHT_SW_VERSION = (1 shl 24) or (15 shl 16) or 0xFF
    private const val STATUSTEXT_LENGTH = 50
    private const val NAME_FIELD_LENGTH = 32
    private const val PARAM_ID_LENGTH = 16

    /** PARAM_EXT_SET / _VALUE / _ACK carry the value as a fixed 128-byte field. */
    private const val PARAM_EXT_VALUE_LENGTH = 128

    /** GIMBAL_DEVICE_FLAGS_YAW_IN_VEHICLE_FRAME: delta_yaw is relative to the aircraft. */
    private const val GIMBAL_FLAGS_YAW_IN_VEHICLE_FRAME = 16

    /** Lyrebird has one gimbal; 0 means "the only one". */
    private const val GIMBAL_DEVICE_ID = 0

    /** Range bounds of the DJI laser rangefinder, in centimetres. */
    private const val LRF_MIN_DISTANCE_CM = 100
    private const val LRF_MAX_DISTANCE_CM = 120_000

    /** LYREBIRD_STATUS_FLAGS, from lyrebird.xml. */
    private const val LB_FLAG_MANUAL_OVERRIDE = 1
    private const val LB_FLAG_READY_TO_TAKEOFF = 2
    private const val LB_FLAG_HOME_SET = 4
    private const val LB_FLAG_LRF_TARGET_VALID = 8
    private const val LB_FLAG_WAYPOINT_REACHED = 16
    private const val LB_FLAG_YAW_REACHED = 32
    private const val LB_FLAG_ALTITUDE_REACHED = 64

    /** char[24] in lyrebird.xml. */
    private const val TAKEOFF_REASON_LENGTH = 24

    /** LYREBIRD_CONFIG field widths, from lyrebird.xml. */
    private const val DRONE_NAME_LENGTH = 20
    private const val IP_ADDRESS_LENGTH = 16
    private const val VIDEO_MODE_LENGTH = 12
    private const val LB_CONFIG_FLAG_HAS_THERMAL = 1

    /** AUTOSENSING field widths, from lyrebird.xml. */
    private const val DETECTION_SOURCE_LENGTH = 16
    private const val DETECTION_TYPE_LENGTH = 16
    private const val MODE_NAME_LENGTH = 35

    /** MAV_FRAME_GLOBAL_RELATIVE_ALT_INT: lat/lon scaled, altitude relative to the home point. */
    private const val MAV_FRAME_GLOBAL_RELATIVE_ALT_INT = 6
    private const val CAM_DEFINITION_URI_LENGTH = 140
    private const val STREAM_URI_LENGTH = 160
    private const val FILE_URL_LENGTH = 205

    /** MAVLink numbers video streams from 1. */
    const val STREAM_ID = 1

    /** MAVLink numbers storage volumes from 1. */
    private const val STORAGE_ID = 1
    private const val FULL_CIRCLE_DEG = 360.0
    private const val HALF_CIRCLE_DEG = 180.0
    private const val MAX_CDEG = 35999

    /** +/-180 degrees in 1e-7 degree units; the widest a latitude or longitude can legally be. */
    private const val MAX_COORD_E7 = 1_800_000_000L
    private const val MIN_COORD_E7 = -1_800_000_000L
    private val IDENTITY_QUATERNION = floatArrayOf(1f, 0f, 0f, 0f)
}
