apply plugin: 'com.android.library'

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-jvm-default=no-compatibility")
    }
}

android {
    namespace = 'dji.v5.ux'
    compileSdk = Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    resourcePrefix = "uxsdk_"
    defaultConfig {
        minSdk = Integer.parseInt(project.ANDROID_MIN_SDK_VERSION)
        targetSdk = Integer.parseInt(project.ANDROID_TARGET_SDK_VERSION)
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    lintOptions {
        checkReleaseBuilds = false
        abortOnError = false
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
}

dependencies {
    implementation rootProject.deps.annotation
    implementation rootProject.deps.appcompat
    implementation rootProject.deps.multidex
    implementation rootProject.deps.legacySupport
    implementation rootProject.deps.recyclerview
    implementation rootProject.deps.okio
    implementation rootProject.deps.wire
    implementation rootProject.deps.constraintLayout
    implementation rootProject.deps.lifecycleJava8
    implementation rootProject.deps.lifecycleRuntime
    implementation rootProject.deps.lifecycleProcess
    implementation rootProject.deps.media
    implementation rootProject.deps.kotlinLib
    implementation rootProject.deps.ktxCore
    implementation rootProject.deps.rx3Android
    implementation rootProject.deps.wpmzSdk
    implementation rootProject.deps.rx3Kt
    implementation rootProject.deps.lottie
    implementation rootProject.deps.cardview
    implementation rootProject.deps.mikepenzCommunityMaterial
    implementation rootProject.deps.mikepenzGoogleMaterial
    implementation rootProject.deps.mikepenzIconicsViews
    implementation rootProject.deps.mikepenzIconicsCore
    implementation rootProject.deps.mikepenzIonicons
    implementation rootProject.deps.material

    api rootProject.deps.maplibreTurf
    api rootProject.deps.maplibreSdk


    api rootProject.deps.playservicesplaces
    api rootProject.deps.playservicesmaps
    api rootProject.deps.playserviceslocation
    api rootProject.deps.playservicesbase

    compileOnly rootProject.deps.aircraftProvided
    implementation rootProject.deps.aircraft

}